    self.connect()
  File "C:\Eluminate\System\ImageScripter\lib\http\client.py", line 928, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:\Eluminate\System\ImageScripter\lib\socket.py", line 727, in create_connection
    raise err
  File "C:\Eluminate\System\ImageScripter\lib\socket.py", line 716, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Eluminate\System\ImageScripter\\Lib\site-packages\imagescripter\core\run.py", line 2, in <module>
    GetBackTOHomeScreenAndStayOn()
  File "C:\Eluminate\Projects\_elan_\elan\functions.py", line 210, in GetBackTOHomeScreenAndStayOn
    GoHomeAndStayOn()
  File "C:\Eluminate\Projects\_elan_\elan\functions.py", line 31, in GoHomeAndStayOn
    GoHome()
  File "C:\Eluminate\Projects\_elan_\elan\functions.py", line 15, in GoHome
    with urllib.request.urlopen(command) as response:
  File "C:\Eluminate\System\ImageScripter\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Eluminate\System\ImageScripter\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Eluminate\System\ImageScripter\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "C:\Eluminate\System\ImageScripter\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Eluminate\System\ImageScripter\lib\urllib\request.py", line 1345, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Eluminate\System\ImageScripter\lib\urllib\request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
